export const FunctionComponent = 0;
export const ClassComponent = 1;
export const IndeterminateComponent = 2; // 在我们知道它是函数还是类之前
export const HostRoot = 3; // 主树的根. 可以嵌套在另一个节点中
export const HostPortal = 4; // 子树。可能是其他渲染器的入口点。
export const HostComponent = 5;
export const HostText = 6;
export const Fragment = 7;
export const Mode = 8;
export const ContextConsumer = 9;
export const ContextProvider = 10;
export const ForwardRef = 11;
export const Profiler = 12;
export const SuspenseComponent = 13;
export const MemoComponent = 14;
export const SimpleMemoComponent = 15;
export const LazyComponent = 16;
export const IncompleteClassComponent = 17;
export const DehydratedFragment = 18;
export const SuspenseListComponent = 19;
export const FundamentalComponent = 20;
export const ScopeComponent = 21;